package eu.dietwise.dao.impl.suggestions;

import java.util.List;
import java.util.UUID;

import eu.dietwise.v1.types.RecipeLanguage;
import io.smallrye.mutiny.Uni;
import org.hibernate.reactive.mutiny.Mutiny;

/**
 * Inserts the Alternative Ingredient, Rule, Suggestion Template and translation rows that DAO tests own outright.
 * <p>
 * A test that asserts a row is absent — no seasonality for a country, no translation of a field — must own that row:
 * the seeded master data is regenerated by the publish tool and fills in values a test cannot predict. Seeding through
 * these helpers keeps such assertions independent of it.
 * <p>
 * The rows are written with native SQL because {@code DW_SUGGESTION_TEMPLATE.alternative_order} is {@code NOT NULL}
 * and is owned by the {@code @OrderColumn} on {@code RuleEntity.alternatives}: persisting the entity graph inserts a
 * template without that column and then updates it, which trips the not-null constraint. Native SQL sets the order
 * directly. Each Rule is given its own Role or Technique so the (recommendation, trigger, role) business key stays
 * unique.
 */
final class SuggestionTemplateFixtures {
	private SuggestionTemplateFixtures() {
	}

	/**
	 * A Suggestion Template to insert: its id, the seeded AlternativeIngredient it suggests, its position within the
	 * Rule, its English restriction, and whether it is active.
	 */
	record Template(UUID id, UUID alternativeIngredientId, int order, String restriction, boolean active) {
	}

	/**
	 * Insert a Rule (with a dedicated Role or Technique) and its templates, reusing the seeded recommendation and
	 * trigger ingredient. Statements run in order so foreign keys resolve; run this inside a transaction.
	 */
	static Uni<Void> insertRuleWithTemplates(
			Mutiny.Session session,
			UUID ruleId,
			UUID recommendationId,
			UUID triggerIngredientId,
			String roleName,
			List<Template> templates
	) {
		UUID roleId = ruleId;
		Uni<Void> chain = session.createNativeQuery("insert into DW_ROLE_OR_TECHNIQUE (id, name) values (:id, :name)")
				.setParameter("id", roleId)
				.setParameter("name", roleName)
				.executeUpdate()
				.chain(() -> session.createNativeQuery(
								"insert into DW_RULE (id, recommendation_id, trigger_ingredient_id, role_or_technique_id) "
										+ "values (:id, :recommendation, :trigger, :role)")
						.setParameter("id", ruleId)
						.setParameter("recommendation", recommendationId)
						.setParameter("trigger", triggerIngredientId)
						.setParameter("role", roleId)
						.executeUpdate())
				.replaceWithVoid();
		for (var template : templates) {
			chain = chain.chain(() -> session.createNativeQuery(
							"insert into DW_SUGGESTION_TEMPLATE "
									+ "(id, rule_id, alternative_ingredient_id, alternative_order, restriction, active) "
									+ "values (:id, :rule, :alternative, :ord, :restriction, :active)")
					.setParameter("id", template.id())
					.setParameter("rule", ruleId)
					.setParameter("alternative", template.alternativeIngredientId())
					.setParameter("ord", template.order())
					.setParameter("restriction", template.restriction())
					.setParameter("active", template.active())
					.executeUpdate()
					.replaceWithVoid());
		}
		return chain;
	}

	/**
	 * Insert an Alternative Ingredient with no seasonality, cost, component for scoring or translation of its own; run
	 * this inside a transaction.
	 */
	static Uni<Void> insertAlternativeIngredient(Mutiny.Session session, UUID id, String name) {
		return session.createNativeQuery("insert into DW_ALTERNATIVE_INGREDIENT (id, name) values (:id, :name)")
				.setParameter("id", id)
				.setParameter("name", name)
				.executeUpdate()
				.replaceWithVoid();
	}

	/**
	 * Insert the translation of a Suggestion Template into one language; a null field is left untranslated. Run this
	 * inside a transaction.
	 */
	static Uni<Void> insertTemplateTranslation(
			Mutiny.Session session,
			UUID templateId,
			RecipeLanguage lang,
			String restriction,
			String equivalence,
			String techniqueNotes
	) {
		return session.createNativeQuery(
						"insert into DW_SUGGESTION_TEMPLATE_TRANSLATION "
								+ "(suggestion_template_id, lang, restriction, equivalence, technique_notes) "
								+ "values (:template, :lang, :restriction, :equivalence, :techniqueNotes)")
				.setParameter("template", templateId)
				.setParameter("lang", lang.name())
				.setParameter("restriction", restriction)
				.setParameter("equivalence", equivalence)
				.setParameter("techniqueNotes", techniqueNotes)
				.executeUpdate()
				.replaceWithVoid();
	}
}
