package eu.dietwise.tools.publish;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

import eu.dietwise.tools.publish.model.Cell;
import eu.dietwise.tools.publish.model.ColumnChange;
import eu.dietwise.tools.publish.model.InsertRow;
import eu.dietwise.tools.publish.model.PublishPlan;
import eu.dietwise.tools.publish.model.TableSnapshot;
import eu.dietwise.tools.publish.model.UpdateRow;
import eu.dietwise.tools.publish.schema.ColumnType;
import eu.dietwise.tools.publish.schema.MirrorSpec;
import eu.dietwise.tools.publish.schema.Tables;

/**
 * Renders a {@link PublishPlan} as a single, self-contained Liquibase changeset in the repository's XML style
 * (tab-indented, {@code dbchangelog-5.0}). The changeset guards itself with a precondition on the Working Copy
 * fingerprint, applies the plan, clears the Working Copy, and carries an explicit rollback that restores both the
 * master data and the Working Copy.
 */
public final class ChangelogRenderer {

	private static final String NEWLINE = "\n";

	private static final Map<String, List<String>> PRIMARY_KEY_BY_MASTER = Tables.all().stream()
			.collect(Collectors.toMap(mirror -> mirror.master().name(), mirror -> mirror.master().primaryKey()));

	public String render(PublishPlan plan, String changeSetId, String author) {
		StringBuilder out = new StringBuilder();
		out.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>").append(NEWLINE);
		out.append("""
				<databaseChangeLog
						xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
						xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
						xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
						xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
						http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-5.0.xsd
						http://www.liquibase.org/xml/ns/dbchangelog-ext
						http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd"
				>
				""");
		line(out, 1, "<changeSet id=\"" + xmlAttr(changeSetId) + "\" author=\"" + xmlAttr(author) + "\">");
		renderPrecondition(out, plan);
		out.append(NEWLINE);
		line(out, 2, "<comment>Publish the Working Copy to the live master data and clear the Working Copy."
				+ " Generated by the dietwise-publish tool.</comment>");
		renderForward(out, plan);
		out.append(NEWLINE);
		renderRollback(out, plan);
		line(out, 1, "</changeSet>");
		out.append("</databaseChangeLog>").append(NEWLINE);
		return out.toString();
	}

	private void renderPrecondition(StringBuilder out, PublishPlan plan) {
		line(out, 2, "<preConditions onFail=\"HALT\" onFailMessage=\""
				+ "The Working Copy changed after this changeset was generated; regenerate and re-apply.\">");
		line(out, 3, "<sqlCheck expectedResult=\"" + plan.workingCopyFingerprint() + "\">"
				+ xmlText(fingerprintSql()) + "</sqlCheck>");
		line(out, 2, "</preConditions>");
	}

	private void renderForward(StringBuilder out, PublishPlan plan) {
		plan.inserts().forEach(insert -> renderInsert(out, 2, insert.table(), insert.cells()));
		plan.updates().forEach(update -> renderUpdate(out, 2, update, ColumnChange::after));
		plan.deletes().forEach(delete -> renderDelete(out, 2, delete.table(), delete.primaryKeyCells()));
		plan.workingCopy().forEach(snapshot -> line(out, 2, "<delete tableName=\"" + snapshot.table() + "\"/>"));
	}

	private void renderRollback(StringBuilder out, PublishPlan plan) {
		line(out, 2, "<rollback>");
		// restore the Working Copy
		for (TableSnapshot snapshot : plan.workingCopy()) {
			for (List<Cell> row : snapshot.rows()) {
				renderInsert(out, 3, snapshot.table(), row);
			}
		}
		// undo master deletes by re-inserting the removed rows (parents before children)
		reversed(plan.deletes()).forEach(delete -> renderInsert(out, 3, delete.table(), delete.row()));
		// undo master updates by restoring the previous values
		reversed(plan.updates()).forEach(update -> renderUpdate(out, 3, update, ColumnChange::before));
		// undo master inserts by deleting the inserted rows (children before parents)
		reversed(plan.inserts()).forEach(insert -> renderDelete(out, 3, insert.table(), primaryKeyCells(insert)));
		line(out, 2, "</rollback>");
	}

	private void renderInsert(StringBuilder out, int indent, String table, List<Cell> cells) {
		line(out, indent, "<insert tableName=\"" + table + "\">");
		for (Cell cell : cells) {
			line(out, indent + 1, "<column name=\"" + cell.column() + "\" " + valueAttribute(cell.type(), cell.value()) + "/>");
		}
		line(out, indent, "</insert>");
	}

	private void renderUpdate(StringBuilder out, int indent, UpdateRow update, Function<ColumnChange, String> value) {
		line(out, indent, "<update tableName=\"" + update.table() + "\">");
		for (ColumnChange change : update.changes()) {
			line(out, indent + 1, "<column name=\"" + change.column() + "\" "
					+ valueAttribute(change.type(), value.apply(change)) + "/>");
		}
		line(out, indent + 1, "<where>" + whereClause(update.primaryKey()) + "</where>");
		line(out, indent, "</update>");
	}

	private void renderDelete(StringBuilder out, int indent, String table, List<Cell> primaryKeyCells) {
		line(out, indent, "<delete tableName=\"" + table + "\">");
		line(out, indent + 1, "<where>" + whereClause(primaryKeyCells) + "</where>");
		line(out, indent, "</delete>");
	}

	private List<Cell> primaryKeyCells(InsertRow insert) {
		List<String> primaryKey = PRIMARY_KEY_BY_MASTER.get(insert.table());
		return insert.cells().stream().filter(cell -> primaryKey.contains(cell.column())).toList();
	}

	private String whereClause(List<Cell> primaryKeyCells) {
		String sql = primaryKeyCells.stream()
				.map(cell -> cell.column() + " = " + sqlLiteral(cell.type(), cell.value()))
				.collect(Collectors.joining(" AND "));
		return xmlText(sql);
	}

	private String fingerprintSql() {
		List<String> terms = new ArrayList<>();
		for (MirrorSpec mirror : Tables.all()) {
			String table = mirror.wc().name().toLowerCase(Locale.ROOT);
			terms.add(mirror.isVersioned()
					? "SELECT count(*)+coalesce(sum(version),0) AS f FROM " + table
					: "SELECT count(*) AS f FROM " + table);
		}
		return "SELECT coalesce(sum(f),0) FROM (" + String.join(" UNION ALL ", terms) + ") counts";
	}

	private String valueAttribute(ColumnType type, String value) {
		if (value == null) {
			return "valueComputed=\"NULL\"";
		}
		return switch (type) {
			case UUID, STRING -> "value=\"" + xmlAttr(value) + "\"";
			case INT, BIGINT -> "valueNumeric=\"" + value + "\"";
			case BOOLEAN -> "valueBoolean=\"" + value + "\"";
		};
	}

	private String sqlLiteral(ColumnType type, String value) {
		return switch (type) {
			case UUID, STRING -> "'" + value.replace("'", "''") + "'";
			case INT, BIGINT, BOOLEAN -> value;
		};
	}

	private static <T> List<T> reversed(List<T> list) {
		List<T> copy = new ArrayList<>(list);
		Collections.reverse(copy);
		return copy;
	}

	private static void line(StringBuilder out, int indent, String text) {
		out.append("\t".repeat(indent)).append(text).append(NEWLINE);
	}

	private static String xmlAttr(String value) {
		return xmlText(value).replace("\"", "&quot;");
	}

	private static String xmlText(String value) {
		return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
	}
}
