-- KEYCLOAK
CREATE USER keycloak WITH PASSWORD 'keycloak';
CREATE SCHEMA AUTHORIZATION keycloak;
ALTER USER keycloak SET search_path = keycloak, public;
GRANT CONNECT ON DATABASE dietwise TO keycloak;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA keycloak TO keycloak;
ALTER SCHEMA keycloak OWNER TO keycloak;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA keycloak GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO keycloak;

-- DIETWISE
CREATE USER dietwise WITH PASSWORD 'dietwise';
CREATE SCHEMA AUTHORIZATION dietwise;
ALTER USER dietwise SET search_path = dietwise, public;
GRANT CONNECT ON DATABASE dietwise TO dietwise;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dietwise TO dietwise;
ALTER SCHEMA dietwise OWNER TO dietwise;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA dietwise GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dietwise;
