# This file contains Quarkus configuration

# HTTP configuration
quarkus.http.port=8180
quarkus.http.test-port=8181
# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://dietwise.ispatial.survey.ntua.gr,/chrome-extension://([a-z0-9-]+)/,/moz-extension://([a-z0-9-]+)/,https://localhost
%dev.quarkus.http.cors.origins=http://localhost:5173,https://gaia.ispatial.survey.ntua.gr,https://gaia.ispatial.survey.ntua.local,/chrome-extension://([a-z0-9-]+)/,/moz-extension://([a-z0-9-]+)/,https://localhost
# Default security headers for API responses (see https://quarkus.io/guides/http-reference#additional-http-headers)
quarkus.http.header."Referrer-Policy".value=no-referrer
quarkus.http.header."Permissions-Policy".value=accelerometer=(), camera=(), geolocation=(), microphone=()
quarkus.http.header."X-Content-Type-Options".value=nosniff
%prod.quarkus.http.header."Strict-Transport-Security".value=max-age=31536000; includeSubDomains
# Our lonely page, extension-callback.html, needs some attention
quarkus.http.header."Cache-Control".value=no-store, max-age=0
quarkus.http.header."Cache-Control".path=/extension-callback.html
quarkus.http.header."Pragma".value=no-cache
quarkus.http.header."Pragma".path=/extension-callback.html
quarkus.http.header."X-Frame-Options".value=DENY
quarkus.http.header."X-Frame-Options".path=/extension-callback.html
quarkus.http.header."Content-Security-Policy".value=default-src 'none'; script-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'
quarkus.http.header."Content-Security-Policy".path=/extension-callback.html

## Datasource configuration (see https://quarkus.io/guides/datasource-guide)
quarkus.datasource.devservices.enabled=false
quarkus.datasource.db-kind=postgresql
## The database connection properties must be set explicitly by the environment
quarkus.datasource.username=INVALID_USERNAME
quarkus.datasource.password=INVALID_PASSWORD
quarkus.datasource.reactive.url=INVALID_URL
quarkus.datasource.jdbc.url=INVALID_URL
quarkus.hibernate-orm.log.sql=false
quarkus.liquibase.change-log=changelog.xml
quarkus.liquibase.migrate-at-start=true

dietwise.version=${project.version}
dietwise.git-hash=${git.commit.id.abbrev}
dietwise.renderer.allow-cached-test-pages=false
%dev.dietwise.renderer.allow-cached-test-pages=true
%test.dietwise.renderer.allow-cached-test-pages=true

quarkus.oidc.auth-server-url=http://localhost:8280/realms/dietwise

# Quarkus Langchain4J configuration - https://docs.quarkiverse.io/quarkus-langchain4j/dev/ollama-chat-model.html
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.extract.base-url=http://localhost:11434
quarkus.langchain4j.ollama.extractNl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.extractEl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.extractLt.base-url=http://localhost:11434
quarkus.langchain4j.ollama.filter.base-url=http://localhost:11434
quarkus.langchain4j.ollama.filterNl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.filterEl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.filterLt.base-url=http://localhost:11434
quarkus.langchain4j.ollama.roleOrTechnique.base-url=http://localhost:11434
quarkus.langchain4j.ollama.roleOrTechniqueNl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.roleOrTechniqueEl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.roleOrTechniqueLt.base-url=http://localhost:11434
quarkus.langchain4j.ollama.triggerIngredient.base-url=http://localhost:11434
quarkus.langchain4j.ollama.triggerIngredientNl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.triggerIngredientEl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.triggerIngredientLt.base-url=http://localhost:11434
quarkus.langchain4j.ollama.ingredientMatchInRecommendations.base-url=http://localhost:11434
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsNl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsEl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsLt.base-url=http://localhost:11434
quarkus.langchain4j.ollama.findBestRule.base-url=http://localhost:11434
quarkus.langchain4j.ollama.findBestRuleNl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.findBestRuleEl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.findBestRuleLt.base-url=http://localhost:11434
quarkus.langchain4j.ollama.suggestAlternatives.base-url=http://localhost:11434
quarkus.langchain4j.ollama.suggestAlternativesNl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.suggestAlternativesEl.base-url=http://localhost:11434
quarkus.langchain4j.ollama.suggestAlternativesLt.base-url=http://localhost:11434
quarkus.langchain4j.ollama.devservices.enabled=false
quarkus.langchain4j.ollama.timeout=300s
quarkus.langchain4j.ollama.extract.timeout=300s
quarkus.langchain4j.ollama.extractNl.timeout=300s
quarkus.langchain4j.ollama.extractEl.timeout=300s
quarkus.langchain4j.ollama.extractLt.timeout=300s
quarkus.langchain4j.ollama.filter.timeout=300s
quarkus.langchain4j.ollama.filterNl.timeout=300s
quarkus.langchain4j.ollama.filterEl.timeout=300s
quarkus.langchain4j.ollama.filterLt.timeout=300s
quarkus.langchain4j.ollama.roleOrTechnique.timeout=300s
quarkus.langchain4j.ollama.roleOrTechniqueNl.timeout=300s
quarkus.langchain4j.ollama.roleOrTechniqueEl.timeout=300s
quarkus.langchain4j.ollama.roleOrTechniqueLt.timeout=300s
quarkus.langchain4j.ollama.triggerIngredient.timeout=300s
quarkus.langchain4j.ollama.triggerIngredientNl.timeout=300s
quarkus.langchain4j.ollama.triggerIngredientEl.timeout=300s
quarkus.langchain4j.ollama.triggerIngredientLt.timeout=300s
quarkus.langchain4j.ollama.ingredientMatchInRecommendations.timeout=300s
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsNl.timeout=300s
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsEl.timeout=300s
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsLt.timeout=300s
quarkus.langchain4j.ollama.findBestRule.timeout=300s
quarkus.langchain4j.ollama.findBestRuleNl.timeout=300s
quarkus.langchain4j.ollama.findBestRuleEl.timeout=300s
quarkus.langchain4j.ollama.findBestRuleLt.timeout=300s
quarkus.langchain4j.ollama.suggestAlternatives.timeout=300s
quarkus.langchain4j.ollama.suggestAlternativesNl.timeout=300s
quarkus.langchain4j.ollama.suggestAlternativesEl.timeout=300s
quarkus.langchain4j.ollama.suggestAlternativesLt.timeout=300s
#quarkus.langchain4j.ollama.chat-model.model-id=llama3.2
quarkus.langchain4j.ollama.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.extract.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.extractNl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.extractEl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.extractLt.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.filter.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.filterNl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.filterEl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.filterLt.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.roleOrTechnique.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.roleOrTechniqueNl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.roleOrTechniqueEl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.roleOrTechniqueLt.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.triggerIngredient.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.triggerIngredientNl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.triggerIngredientEl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.triggerIngredientLt.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.ingredientMatchInRecommendations.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsNl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsEl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsLt.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.findBestRule.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.findBestRuleNl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.findBestRuleEl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.findBestRuleLt.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.suggestAlternatives.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.suggestAlternativesNl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.suggestAlternativesEl.chat-model.model-id=llama3.1:8b
quarkus.langchain4j.ollama.suggestAlternativesLt.chat-model.model-id=llama3.1:8b
# Would be nice to use the Recipe schema and output JSON here!
#quarkus.langchain4j.ollama.chat-model.format=
quarkus.langchain4j.ollama.extract.chat-model.format={"type":"object","properties":\
    {"name":{"type":["string","null"]},\
    "recipeYield":{"type":["string","null"]},\
    "recipeIngredients":{"type":"array","items":{"type":"string"}},\
    "recipeInstructions":{"type":"array","items":{"type":"string"}}\
  },"required":["recipeIngredients","recipeInstructions"]}
# Full Ollama interaction logging, for development only
#%dev.quarkus.langchain4j.ollama.log-requests=true
#%dev.quarkus.langchain4j.ollama.extract.log-requests=true
#%dev.quarkus.langchain4j.ollama.filter.log-requests=true
#%dev.quarkus.langchain4j.ollama.roleOrTechnique.log-requests=true
#%dev.quarkus.langchain4j.ollama.triggerIngredient.log-requests=true
#%dev.quarkus.langchain4j.ollama.ingredientMatchInRecommendations.log-requests=true
#%dev.quarkus.langchain4j.ollama.findBestRule.log-requests=true
#%dev.quarkus.langchain4j.ollama.suggestAlternatives.log-requests=true
#%dev.quarkus.langchain4j.ollama.log-responses=true
#%dev.quarkus.langchain4j.ollama.extract.log-responses=true
#%dev.quarkus.langchain4j.ollama.filter.log-responses=true
#%dev.quarkus.langchain4j.ollama.roleOrTechnique.log-responses=true
#%dev.quarkus.langchain4j.ollama.triggerIngredient.log-responses=true
#%dev.quarkus.langchain4j.ollama.ingredientMatchInRecommendations.log-responses=true
#%dev.quarkus.langchain4j.ollama.findBestRule.log-responses=true
#%dev.quarkus.langchain4j.ollama.suggestAlternatives.log-responses=true
# Play
# default: 0.8 - lower is more conservative
#quarkus.langchain4j.ollama.chat-model.temperature=0.8
quarkus.langchain4j.ollama.extract.chat-model.temperature=0.3
quarkus.langchain4j.ollama.extractNl.chat-model.temperature=0.3
quarkus.langchain4j.ollama.extractEl.chat-model.temperature=0.3
quarkus.langchain4j.ollama.extractLt.chat-model.temperature=0.3
quarkus.langchain4j.ollama.filter.chat-model.temperature=0.3
quarkus.langchain4j.ollama.filterNl.chat-model.temperature=0.3
quarkus.langchain4j.ollama.filterEl.chat-model.temperature=0.3
quarkus.langchain4j.ollama.filterLt.chat-model.temperature=0.3
quarkus.langchain4j.ollama.roleOrTechnique.chat-model.temperature=0
quarkus.langchain4j.ollama.roleOrTechniqueNl.chat-model.temperature=0
quarkus.langchain4j.ollama.roleOrTechniqueEl.chat-model.temperature=0
quarkus.langchain4j.ollama.roleOrTechniqueLt.chat-model.temperature=0
#quarkus.langchain4j.ollama.roleOrTechnique.chat-model.top-p=0.1
#quarkus.langchain4j.ollama.roleOrTechnique.chat-model.top-k=20
quarkus.langchain4j.ollama.roleOrTechnique.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.roleOrTechniqueNl.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.roleOrTechniqueEl.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.roleOrTechniqueLt.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.roleOrTechnique.chat-model.num-predict=20
quarkus.langchain4j.ollama.roleOrTechniqueNl.chat-model.num-predict=20
quarkus.langchain4j.ollama.roleOrTechniqueEl.chat-model.num-predict=20
quarkus.langchain4j.ollama.roleOrTechniqueLt.chat-model.num-predict=20
quarkus.langchain4j.ollama.triggerIngredient.chat-model.temperature=0
quarkus.langchain4j.ollama.triggerIngredientNl.chat-model.temperature=0
quarkus.langchain4j.ollama.triggerIngredientEl.chat-model.temperature=0
quarkus.langchain4j.ollama.triggerIngredientLt.chat-model.temperature=0
#quarkus.langchain4j.ollama.triggerIngredient.chat-model.top-p=0.1
#quarkus.langchain4j.ollama.triggerIngredient.chat-model.top-k=20
quarkus.langchain4j.ollama.triggerIngredient.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.triggerIngredientNl.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.triggerIngredientEl.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.triggerIngredientLt.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.triggerIngredient.chat-model.num-predict=20
quarkus.langchain4j.ollama.triggerIngredientNl.chat-model.num-predict=20
quarkus.langchain4j.ollama.triggerIngredientEl.chat-model.num-predict=20
quarkus.langchain4j.ollama.triggerIngredientLt.chat-model.num-predict=20
quarkus.langchain4j.ollama.ingredientMatchInRecommendations.chat-model.temperature=0
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsNl.chat-model.temperature=0
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsEl.chat-model.temperature=0
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsLt.chat-model.temperature=0
#quarkus.langchain4j.ollama.ingredientMatchInRecommendations.chat-model.top-p=0.1
#quarkus.langchain4j.ollama.ingredientMatchInRecommendations.chat-model.top-k=20
quarkus.langchain4j.ollama.ingredientMatchInRecommendations.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsNl.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsEl.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsLt.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.ingredientMatchInRecommendations.chat-model.num-predict=8
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsNl.chat-model.num-predict=8
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsEl.chat-model.num-predict=8
quarkus.langchain4j.ollama.ingredientMatchInRecommendationsLt.chat-model.num-predict=8
quarkus.langchain4j.ollama.findBestRule.chat-model.temperature=0
quarkus.langchain4j.ollama.findBestRuleNl.chat-model.temperature=0
quarkus.langchain4j.ollama.findBestRuleEl.chat-model.temperature=0
quarkus.langchain4j.ollama.findBestRuleLt.chat-model.temperature=0
#quarkus.langchain4j.ollama.findBestRule.chat-model.top-p=0.1
#quarkus.langchain4j.ollama.findBestRule.chat-model.top-k=20
quarkus.langchain4j.ollama.findBestRule.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.findBestRuleNl.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.findBestRuleEl.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.findBestRuleLt.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.findBestRule.chat-model.num-predict=8
quarkus.langchain4j.ollama.findBestRuleNl.chat-model.num-predict=8
quarkus.langchain4j.ollama.findBestRuleEl.chat-model.num-predict=8
quarkus.langchain4j.ollama.findBestRuleLt.chat-model.num-predict=8
quarkus.langchain4j.ollama.suggestAlternatives.chat-model.temperature=0
quarkus.langchain4j.ollama.suggestAlternativesNl.chat-model.temperature=0
quarkus.langchain4j.ollama.suggestAlternativesEl.chat-model.temperature=0
quarkus.langchain4j.ollama.suggestAlternativesLt.chat-model.temperature=0
#quarkus.langchain4j.ollama.suggestAlternatives.chat-model.top-p=0.1
#quarkus.langchain4j.ollama.suggestAlternatives.chat-model.top-k=20
quarkus.langchain4j.ollama.suggestAlternatives.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.suggestAlternativesNl.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.suggestAlternativesEl.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.suggestAlternativesLt.chat-model.repeat-penalty=1.1
quarkus.langchain4j.ollama.suggestAlternatives.chat-model.num-predict=40
quarkus.langchain4j.ollama.suggestAlternativesNl.chat-model.num-predict=40
quarkus.langchain4j.ollama.suggestAlternativesEl.chat-model.num-predict=40
quarkus.langchain4j.ollama.suggestAlternativesLt.chat-model.num-predict=40
# default: 0.9 - lower is more focused & conservative
quarkus.langchain4j.ollama.chat-model.top-p=0.9
# default: 40 - lower is more conservative
quarkus.langchain4j.ollama.chat-model.top-k=40

# See https://quarkus.io/guides/rest#accessing-request-parameters
%dev.quarkus.log.category."org.jboss.resteasy.reactive.server.handlers.ParameterHandler".level=DEBUG
%dev.quarkus.log.category."eu.dietwise.services.v1.suggestions.impl.RecipeSuggestionsServiceImpl".level=DEBUG
%dev.quarkus.log.category."eu.dietwise.services.v1.scoring.impl.ScoringAiFacadeImpl".level=DEBUG

quarkus.rest-client.renderer.url=http://localhost:3000/
